version: '3.8'

services:
  postgres:
    build:
      context: .
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
